janitor:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers --------------------------------------
  twist_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: twist_joint
    pid: {p: 100.0, i: 80.0, d: 70.0}
  prismatic_vertical_position_controller:
    type: effort_controllers/JointPositionController
    joint: prismatic_vertical
    pid: {p: 1700.0, i: 140.0, d: 280.0}
  prismatic_horizontal_position_controller:
    type: effort_controllers/JointPositionController
    joint: prismatic_horizontal
    pid: {p: 100.0, i: 90.0, d: 80.0}
  prismatic_gripper_position_controller:
    type: effort_controllers/JointPositionController
    joint: prismatic_gripper
    pid: {p: 10.0, i: 5.0, d: 2.50}
